repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        exclude: ^migrations/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0
    hooks:
      - id: prettier
        files: \.(ts|tsx|js|jsx|scss|css)$
        exclude_types: [html]
        exclude: frontend/src/store/api.ts

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        exclude: api/tests/.*
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.3.0"
    hooks:
      - id: eslint
        exclude: ^models/
        verbose: true
        args:
          - --color
          - --fix

  - repo: local
    hooks:
      - id: openapi
        name: check-openapi-spec-file
        language: script
        entry: ./scripts/generate_swagger.sh
